[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor
loglevel=info
logfile_maxbytes=50MB
logfile_backups=20
silent=false
user=root

[program:sshd]
command=/opt/ssh/start-ssh.sh
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/sshd.err.log
stdout_logfile=/var/log/supervisor/sshd.out.log
priority=10
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
redirect_stderr=true
stdout_capture_maxbytes=50MB
stderr_capture_maxbytes=50MB
stdout_events_enabled=false
stderr_events_enabled=false
logfile_backups=20

[program:code-server]
command=/opt/code-server/start-code-server.sh
directory=/opt/code-server
environment=PYTHONUNBUFFERED=1
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/code-server.err.log
stdout_logfile=/var/log/supervisor/code-server.out.log
priority=20
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
redirect_stderr=true
stdout_capture_maxbytes=50MB
stderr_capture_maxbytes=50MB
stdout_events_enabled=true
stderr_events_enabled=true
logfile_backups=20


[inet_http_server]
port=*:9001
username=%(ENV_SUPERVISORD_USER)s
password=%(ENV_SUPERVISORD_PASS)s

[supervisorctl]
serverurl=http://localhost:9001
username=%(ENV_SUPERVISORD_USER)s
password=%(ENV_SUPERVISORD_PASS)s
